#!/bin/bash
cd "$(dirname "$0")"
echo - Building JavaScript

cat src/js/server.js src/js/App.jsx > dist/main_min.jsx
npx babel dist/main_min.jsx -d dist
rm dist/main_min.jsx


cd "$(dirname "$0")"
echo - Building CSS

cat src/css/component.css src/css/main.css  > dist/main_min.css

cp -r src/images dist
cp src/index.html dist/index.html

echo \|-------------------\|
echo \| Finished Building \|
echo \|-------------------\|
